### ISSUE TITLE
Running go generate changes go.mod

### ISSUE THREAD

**Issue by jdhenke** [ent/ent#3207]
Running go generate changes go.mod in a way that `go mod tidy` reverses.

This breaks CI when checking to ensure that `go.mod` is up to date.

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

```
(show-bug)$ cat services/index/internal/ent/generate.go 
package ent

//go:generate go run -mod=mod entgo.io/ent/cmd/ent generate ./schema --feature sql/upsert
(show-bug)$ go generate ./services/index/internal/ent 
(show-bug *)$ git diff
diff --git a/go.sum b/go.sum
index d4362e6..b9cd9c9 100644
--- a/go.sum
+++ b/go.sum
@@ -38,6 +38,7 @@ github.com/kr/text v0.2.0 h1:5Nx0Ya0ZqY2ygV366QzturHI13Jq95ApcVaJBhpS+AY=
 github.com/kylelemons/godebug v0.0.0-20170820004349-d65d576e9348 h1:MtvEpTB6LX3vkb4ax0b5D2DHbNAUsen0Gx5wZoq3lV4=
 github.com/lib/pq v1.10.7 h1:p7ZhMD+KsSRozJr34udlUrhboJwWAgCg34+/ZZNvZZw=
 github.com/lib/pq v1.10.7/go.mod h1:AlVN5x4E4T544tWzH6hKfbfQvm3HdbOxrmggDNAPY9o=
+github.com/mattn/go-runewidth v0.0.9 h1:Lm995f3rfxdpd6TSmuVCHVb/QhupuXlYr8sCI/QdE+0=
 github.com/mattn/go-sqlite3 v1.14.16 h1:yOQRA0RpS5PFz/oikGwBEqvAWhWg5ufRz4ETLjwpU1Y=
 github.com/minio/highwayhash v1.0.2 h1:Aak5U0nElisjDCfPSG79Tgzkn2gl66NxOMspRrKnA/g=
 github.com/minio/highwayhash v1.0.2/go.mod h1:BQskDq+xkJ12lmlUUi7U0M5Swg3EWR+dLTk+kldvVxY=
@@ -53,9 +54,12 @@ github.com/nats-io/nkeys v0.3.0 h1:cgM5tL53EvYRU+2YLXIK0G2mJtK12Ft9oeooSZMA2G8=
 github.com/nats-io/nkeys v0.3.0/go.mod h1:gvUNGjVcM2IPr5rCsRsC6Wb3Hr2CQAm08dsxtV6A5y4=
...skipping...
 github.com/sergi/go-diff v1.0.0 h1:Kpca3qRNrduNnOQeazBd0ysaKrUJiIuISHxogkT9RPQ=
+github.com/spf13/cobra v1.6.1 h1:o94oiPyS4KD1mPy2fmcYYHHfCxLqYjJOhGsCHFZtEzA=
+github.com/spf13/pflag v1.0.5 h1:iy+VFUOCP1a+8yFto/drg2CJ5u0yRoB7fZw3DKv/JXA=
 github.com/stretchr/objx v0.1.0/go.mod h1:HFkY916IF+rwdDfMAkV7OtwuqBVzrE8GR6GFx+wExME=
 github.com/stretchr/objx v0.4.0/go.mod h1:YvHI0jy2hoMjB+UWwv71VJQ9isScKT/TqJzVSSt89Yw=
 github.com/stretchr/objx v0.5.0/go.mod h1:Yh+to48EsGEfYuaHDzXPcE3xhTkx73EhmCGUpEOglKo=
@@ -93,6 +97,7 @@ golang.org/x/text v0.5.0/go.mod h1:mrYo+phRRbMaCq/xk9113O4dZlRixOauAjOtrjsXDZ8=
 golang.org/x/time v0.0.0-20220922220347-f3bd1da661af h1:Yx9k8YCG3dvF87UAn2tu2HQLf2dt/eR1bXxpLMWeH+Y=
 golang.org/x/time v0.0.0-20220922220347-f3bd1da661af/go.mod h1:tRJNPiyCQ0inRvYxbN9jk5I+vvW/OXSQhTDSoE431IQ=
 golang.org/x/tools v0.0.0-20180917221912-90fa682c2a6e/go.mod h1:n7NCudcB/nEzxVGmLbDWY5pfWTLqBcC2KZ6jyYvM4mQ=
+golang.org/x/tools v0.3.1-0.20221202221704-aa9f4b2f3d57 h1:/X0t/E4VxbZE7MLS7auvE7YICHeVvbIa9vkOVvYW/24=
 golang.org/x/xerrors v0.0.0-20191204190536-9bdfabe68543/go.mod h1:I/5z698sn9Ka8TeJc9MKroUUfqBBauWjQqLJ2OPfmY0=
 golang.org/x/xerrors v0.0.0-20200804184101-5ec99f83aff1 h1:go1bK/D/BFZV2I8cIQd1NKEZ+0owSTG1fDTci4IqFcE=
 google.golang.org/appengine v1.6.5/go.mod h1:8WjMMxjGQR8xUklV/ARdw2HLXBOI7O7uCIDZVag1xfc=
 github.com/sergi/go-diff v1.0.0 h1:Kpca3qRNrduNnOQeazBd0ysaKrUJiIuISHxogkT9RPQ=
+github.com/spf13/cobra v1.6.1 h1:o94oiPyS4KD1mPy2fmcYYHHfCxLqYjJOhGsCHFZtEzA=
+github.com/spf13/pflag v1.0.5 h1:iy+VFUOCP1a+8yFto/drg2CJ5u0yRoB7fZw3DKv/JXA=
 github.com/stretchr/objx v0.1.0/go.mod h1:HFkY916IF+rwdDfMAkV7OtwuqBVzrE8GR6GFx+wExME=
 github.com/stretchr/objx v0.4.0/go.mod h1:YvHI0jy2hoMjB+UWwv71VJQ9isScKT/TqJzVSSt89Yw=
 github.com/stretchr/objx v0.5.0/go.mod h1:Yh+to48EsGEfYuaHDzXPcE3xhTkx73EhmCGUpEOglKo=
@@ -93,6 +97,7 @@ golang.org/x/text v0.5.0/go.mod h1:mrYo+phRRbMaCq/xk9113O4dZlRixOauAjOtrjsXDZ8=
 golang.org/x/time v0.0.0-20220922220347-f3bd1da661af h1:Yx9k8YCG3dvF87UAn2tu2HQLf2dt/eR1bXxpLMWeH+Y=
 golang.org/x/time v0.0.0-20220922220347-f3bd1da661af/go.mod h1:tRJNPiyCQ0inRvYxbN9jk5I+vvW/OXSQhTDSoE431IQ=
 golang.org/x/tools v0.0.0-20180917221912-90fa682c2a6e/go.mod h1:n7NCudcB/nEzxVGmLbDWY5pfWTLqBcC2KZ6jyYvM4mQ=
+golang.org/x/tools v0.3.1-0.20221202221704-aa9f4b2f3d57 h1:/X0t/E4VxbZE7MLS7auvE7YICHeVvbIa9vkOVvYW/24=
 golang.org/x/xerrors v0.0.0-20191204190536-9bdfabe68543/go.mod h1:I/5z698sn9Ka8TeJc9MKroUUfqBBauWjQqLJ2OPfmY0=
 golang.org/x/xerrors v0.0.0-20200804184101-5ec99f83aff1 h1:go1bK/D/BFZV2I8cIQd1NKEZ+0owSTG1fDTci4IqFcE=
 google.golang.org/appengine v1.6.5/go.mod h1:8WjMMxjGQR8xUklV/ARdw2HLXBOI7O7uCIDZVag1xfc=

(show-bug *)$ go mod tidy
(show-bug)$ git diff
(show-bug)$ 
```

## Expected Behavior 🤔

I would expect this to not change `go.mod`

## Steps to Reproduce 🕹

Steps:

See above

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | go version go1.19.4 darwin/amd64  |
| Ent         | entgo.io/ent v0.11.5-0.20230102205927-542f36d4abda  |
| Database    | PostgreSQL   |plat
| Driver      | https://github.com/lib/pq        |

**Comment by a8m** [comment]
Hey hey 👋 
As suggested by @masseelch on our Discord, using `entc` as a package should solve this issue: https://entgo.io/docs/code-gen/#use-entc-as-a-package. Please, give it a try and update.

**Comment by jdhenke** [comment]
Repro is here: https://github.com/jdhenke/ent-3207

1. ⚠️ NOTE: https://github.com/jdhenke/ent-3207 is not a valid file because it has an unused import statement.
2. 👍 Updated `master` to use `entc.go` approach in [this commit](https://github.com/jdhenke/ent-3207/commit/6fedf9a9fb857db8ce44712f9dcaad5daa781897)
3. ❌ Showed the diff you still see in `go.mod` here even using `entc.go` when you run `go mod tidy` in [this MR](https://github.com/jdhenke/ent-3207/pull/1/files)

I think this is because `go mod tidy` ignores `entc.go` because of the `ignore` build tag. This is expected behavior from the docs: https://go.dev/ref/mod#go-mod-tidy

✅ Googling around more generally, I think I'm essentially hitting this https://github.com/golang/go/issues/45552 which recommends using [the `tools.go` idiom](https://github.com/golang/go/wiki/Modules#how-can-i-track-tool-dependencies-for-a-module) I was able to get the bug example to a stable place: https://github.com/jdhenke/ent-3207/pull/2

🙋‍♂️ Do you think that such a `tools.go` file could be added to ent? Would this remove the need to specify `-mod=mod` everywhere?

**Comment by a8m** [comment]
Thanks for writing this detailed report, @jdhenke 🙏 

> 🙋‍♂️ Do you think that such a `tools.go` file could be added to ent? Would this remove the need to specify -mod=mod everywhere?

It feels like a project-specific setup that can be handled once rather than adding to Ent. Another alternative is to add `go mod tidy` inside `ent/generate.go` right after the codegen command. 

Many users (like us for example, the maintainers) don't use the default `ent/generate.go` file - @giautm and I create a `generate.go` file in the root of the project and combine there all the different codegen commands for our projects (ent, gqlgen, wire, etc). This is why I'm OK with giving users the freedom to configure their projects however they want.

**Comment by jdhenke** [comment]
Gotcha.

Perhaps a link could be added to the [tools.go idiom](https://github.com/golang/go/wiki/Modules#how-can-i-track-tool-dependencies-for-a-module) in the ent code gen docs here https://entgo.io/docs/code-gen in case someone wants to use ent and ensure their repo is always `go mod tidy`, that can be headed off in the docs and without the need to bother you on discord. 

Also, including a `tools.go` would enable dropping the need for specifying `-mod=mod` everywhere, which feels like a win.

Just some thoughts. Ultimately, this is good to close from my end :+1:

**Comment by a8m** [comment]
> Perhaps a link could be added to the [tools.go idiom](https://github.com/golang/go/wiki/Modules#how-can-i-track-tool-dependencies-for-a-module) in the ent code gen docs here https://entgo.io/docs/code-gen in case someone wants to use ent and ensure their repo is always `go mod tidy`, that can be headed off in the docs and without the need to bother you on discord.

You're more than welcome to contribute improvements to our docs 🙏 

Thanks again for the detailed report on this issue and #3208.
